# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekBlogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='geekblogdb',
            name='slug',
            field=models.SlugField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geekblogdb',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekBlogger.UserName'),
        ),
    ]
