# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geekBlogger', '0002_auto_20160730_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geekblogdb',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='geekblogdb',
            name='userName',
        ),
        migrations.AddField(
            model_name='geekblogdb',
            name='author',
            field=models.ForeignKey(default='unauthorized', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geekblogdb',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
