# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekBlogger', '0003_auto_20160730_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekblogdb',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
